--------------------------------------------------------
--info:battle
--author:Yutao
--date:2018/3/14 22:32:59
--------------------------------------------------------

battle={
[22] = {
    ["score"] = "10",
    ["battle_id"] = "22",
    ["event_value"] = "reward_4",
    ["event_type"] = "reward",
    ["tips"] = "恭喜!",
},
[27] = {
    ["score"] = "10",
    ["battle_id"] = "27",
    ["event_value"] = "-4",
    ["event_type"] = "move",
    ["tips"] = "后退4步",
},
[26] = {
    ["score"] = "10",
    ["battle_id"] = "26",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[25] = {
    ["score"] = "10",
    ["battle_id"] = "25",
    ["event_value"] = "1",
    ["event_type"] = "move",
    ["tips"] = "前进1步",
},
[24] = {
    ["score"] = "10",
    ["battle_id"] = "24",
    ["event_value"] = "-5",
    ["event_type"] = "move",
    ["tips"] = "后退5步",
},
[23] = {
    ["score"] = "10",
    ["battle_id"] = "23",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[28] = {
    ["score"] = "10",
    ["battle_id"] = "28",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[21] = {
    ["score"] = "10",
    ["battle_id"] = "21",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[20] = {
    ["score"] = "10",
    ["battle_id"] = "20",
    ["event_value"] = "3",
    ["event_type"] = "move",
    ["tips"] = "前进3步",
},
[19] = {
    ["score"] = "10",
    ["battle_id"] = "19",
    ["event_value"] = "reward_1",
    ["event_type"] = "reward",
    ["tips"] = "恭喜获得20元代金卷",
},
[18] = {
    ["score"] = "10",
    ["battle_id"] = "18",
    ["event_value"] = "1",
    ["event_type"] = "move",
    ["tips"] = "前进1步",
},
[9] = {
    ["score"] = "10",
    ["battle_id"] = "9",
    ["event_value"] = "-4",
    ["event_type"] = "move",
    ["tips"] = "后退4步",
},
[1] = {
    ["score"] = "10",
    ["battle_id"] = "1",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[15] = {
    ["score"] = "10",
    ["battle_id"] = "15",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[3] = {
    ["score"] = "10",
    ["battle_id"] = "3",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[2] = {
    ["score"] = "10",
    ["battle_id"] = "2",
    ["event_value"] = "2",
    ["event_type"] = "move",
    ["tips"] = "前进2步",
},
[5] = {
    ["score"] = "10",
    ["battle_id"] = "5",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[4] = {
    ["score"] = "10",
    ["battle_id"] = "4",
    ["event_value"] = "-3",
    ["event_type"] = "move",
    ["tips"] = "后退3步",
},
[7] = {
    ["score"] = "10",
    ["battle_id"] = "7",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[6] = {
    ["score"] = "10",
    ["battle_id"] = "6",
    ["event_value"] = "reward_2",
    ["event_type"] = "reward",
    ["tips"] = "恭喜获得50元代金卷",
},
[14] = {
    ["score"] = "10",
    ["battle_id"] = "14",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[8] = {
    ["score"] = "10",
    ["battle_id"] = "8",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[16] = {
    ["score"] = "10",
    ["battle_id"] = "16",
    ["event_value"] = "reward_3",
    ["event_type"] = "reward",
    ["tips"] = "恭喜!",
},
[17] = {
    ["score"] = "10",
    ["battle_id"] = "17",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[13] = {
    ["score"] = "10",
    ["battle_id"] = "13",
    ["event_value"] = "4",
    ["event_type"] = "move",
    ["tips"] = "前进4步",
},
[12] = {
    ["score"] = "10",
    ["battle_id"] = "12",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[11] = {
    ["score"] = "10",
    ["battle_id"] = "11",
    ["event_value"] = "0",
    ["event_type"] = "null",
    ["tips"] = "无",
},
[10] = {
    ["score"] = "10",
    ["battle_id"] = "10",
    ["event_value"] = "reward_1",
    ["event_type"] = "reward",
    ["tips"] = "恭喜获得20元代金卷",
},
}return battle